### ISSUE TITLE
avisota/contao-bundle-all ~3.1 cannot be installed

### ISSUE THREAD

**Issue by fritzmg** [avisota/contao-core#217]
When trying to install `"avisota/contao-bundle-all": "~3.1"` via composer with `"minimum-stability": "stable"`, the operation fails with

```
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for avisota/contao-bundle-all ~3.1 -> satisfiable by avisota/contao-bundle-all[3.1.0].
- avisota/contao-bundle-all 3.1.0 requires avisota/contao-message-element-image ~3.1 -> no matching package found.
```

Because `avisota/contao-bundle-all` `3.1` requires `"avisota/contao-message-element-image": "~3.1"`, however there is no `3.1` release for `avisota/contao-message-element-image`. There is only a `3.0.1` release.

**Comment by baumannsven** [comment]
Can you test this with avisota/contao-bundle-all 3.2.

**Comment by baumannsven** [comment]
This problem is fixed.
