### ISSUE TITLE
Images become scaled in newsletter

### ISSUE THREAD

**Issue by richardhj** [avisota/contao-core#221]
I created a newsletter which includes images. The sent preview was fine.
After sending the newsletter (I had to re-trigger the queue in the backend) I noticed, all images were scaled to a maximum size of 320px.
I really don't know, how this could happen. After all, maybe this can be the source of fault: https://github.com/contao-community-alliance/twig/blob/master/src/ContaoTwig/ContaoTwigExtension.php#L481

**Comment by kroka** [comment]
I'm affected as well. Thanks for your hint, @richardhj.

Replacing the line mentioned above in _composer/vendor/contao-community-alliance/contao-twig/src/ContaoTwig_ by `$intMaxWidth = $GLOBALS['TL_CONFIG']['maxImageWidth']` fixes the bug, but that's obviously not a solution.
