### ISSUE TITLE
Errors with Nightly Build

### ISSUE THREAD

**Issue by xApep** [avisota/contao-core#222]
Hi. On windows we cannot use composer so I have download Nightly Build (zip) version from official avisota.org website.

Now if I want to setup avisota (click on Message, Recipient, Settings -> mailing list, etc.) I get bunch of errors in back-end, usually there is the same error (attachment).
![fireshot screen capture 038 - - localhost_avisota_contao_main_php_do avisota_recipients ref d6c7137c](https://cloud.githubusercontent.com/assets/1315340/17573090/6f380f2c-5f58-11e6-96da-14c22be67774.png)

An idea of what is going on? I have Contao 3.5.14 clean install, I have updated db...

**Comment by baumannsven** [comment]
@xApep can you test if this problem comes with the current version?

**Comment by hh-com** [comment]
Ich würde es testen, die Download-Site ist aber gerade off:
http://avisota.org/de/avisota/download

**Comment by baumannsven** [comment]
@xApep Do you have test this again?

**Comment by xApep** [comment]
Sorry but no. We switched to MailerLite for Mail marketing.

Kind regards.
