### ISSUE TITLE
Inserttags not working

### ISSUE THREAD

**Issue by kroka** [avisota/contao-core#226]
Using the latest release of Avisota none of the inserttags seems to work inside a newsletter.
I've tried tags such as `{{newsletter::unsubscribe}} {{newsletter::unsubscribe_url}} {{newsletter::href}}` and the simple tags like `##recipient.unsubscribe_link.url## ##recipient.unsubscribe_link.text##`.

Inside _composer/vendor/avisota/contao-core/contao/config_ the line `$GLOBALS['TL_HOOKS']['replaceInsertTags'][]       = array('AvisotaInsertTag', 'hookReplaceNewsletterInsertTags');` is commented out and the class `AvisotaInsertTag` is only located inside _composer/vendor/avisota/contao-core/system_remove_ and no longer in use?

- contao/core 3.5.25
- avisota/contao-bundle-all 3.2.0

**Comment by kroka** [comment]
_push_

Is Avisota still alive?

**Comment by baumannsven** [comment]
@kroka avisota be alive.

I show for this problem

**Comment by kroka** [comment]
Sorry, but is this really fixed? The insert tags are still not working for me after updating to _avisota/contao-core_ 3.2.2.
Moreover, I neither can find any code related to insert tags in the latest commits (such as https://github.com/avisota/contao-core/commit/dc85b9e4c24d3aa0f6f4f1a3e46809c2cace3677) nor do I find the registration of an _replaceInsertTags_ hook.

**Comment by baumannsven** [comment]
@kroka the holder system_remove is the old avisota folder. This folder not working.
The AvisotaInsertTag class is depcrated a long time. You must use simple tokens.

**Comment by kroka** [comment]
I've also tried  `##recipient.unsubscribe_link.url## ` and `##recipient.unsubscribe_link.text##` inside a text element without success. However, the simple token `##view_online_link##` is working.

By the way: shouldn't Avisota insert a default footer that includes the unsubscribe link automatically? That's not the case for me. Seems like the condition `if recipient.manage_subscription_link is defined` in the template is not true. Shall I open another issue?
