### ISSUE TITLE
Abonnentenliste als CSV Datei

### ISSUE THREAD

**Issue by Ainschy** [avisota/contao-core#230]
Bei dem Newsletter Versandt an eine CSV Abonnentenliste hängt sich der Versandt in einen Reload auf und es findet kein Versand statt. Die Anzahl der Empfänger wird mit 0 angezeigt, obwohl Adressen vorhanden sind.

Version:
Contao 3.5.27
Avisota Bundle All : 3.2.0

**Comment by baumannsven** [comment]
Hier gibt es generell ein Problem. Die Url für den Subrequest wir nicht richtig erstellt.
https://github.com/avisota/contao-core/blob/master/src/Backend/Outbox.php#L106

**Comment by baumannsven** [comment]
Das Problem wurde behoben.
