### ISSUE TITLE
Kein Versand mehr möglich

### ISSUE THREAD

**Issue by Floxn** [avisota/contao-core#233]
Bei einem Newsletterversand eines Kunden ist der Versand in einer Dauerschleife und geht nicht weiter. Zum Glück schon beim "Vorgbereiten"
![newsletter umzug-danke_2017-07-24](https://user-images.githubusercontent.com/15326334/28530483-463d5872-7094-11e7-983a-0f94eb6b8012.JPG)

Hier ist noch der Error-Log

> [24-Jul-2017 17:10:53 Europe/Berlin] 
PHP Warning: Invalid argument supplied for foreach() in /www/htdocs/xxx/composer/vendor/avisota/contao-core/src/Backend/Outbox.php on line 128
#0 /www/htdocs/xxx/composer/vendor/avisota/contao-core/src/Backend/Outbox.php(128): __error(2, 'Invalid argumen...', '/www/htdocs/w01...', 128, Array)
#1 /www/htdocs/xxx/composer/vendor/avisota/contao-core/src/Backend/Outbox.php(89): Avisota\Contao\Core\Backend\Outbox->sendImmediate()
#2 /www/htdocs/xxx/composer/vendor/contao-community-alliance/contao-twig/src/ContaoTwig/TwigBackendModule.php(45): Avisota\Contao\Core\Backend\Outbox->compile()
#3 /www/htdocs/xxx/system/modules/core/classes/Backend.php(423): TwigBackendModule->generate()
#4 /www/htdocs/xxx/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('avisota_outbox')
#5 /www/htdocs/xxx/contao/main.php(20): Contao\BackendMain->run()
#6 {main}

System:
Contao: 3.5.28
avisota/contao-bundle-all: 3.2.0

**Comment by kroka** [comment]
Der Fehler trat bei mir nach einem Server-Umzug ebenfalls. Ursächlich ist folgende Zeile 106 in _composer/vendor/avisota/contao-core/src/Backend/Outbox.php_:

```
$requestUrlBuilder->setHost(Environment::get('requestScheme') . '://' . Environment::get('host'))
```

Die Umgebungsvariable `REQUEST_SCHEME` wird allerdings nicht bei allen Webservern gesetzt (siehe auch https://stackoverflow.com/q/18008135), weshalb die Request in Zeile 119 ins Leere führt, was letztlich den Fehler in Zeile 128 auslöst.

Hier im Repo ist der Fehler aber anscheinend schon gefixt: https://github.com/avisota/contao-core/blob/master/src/Backend/Outbox.php#L109
