### ISSUE TITLE
Empfängerquellen: Auflisten der Empfänger löst Fatal Error aus

### ISSUE THREAD

**Issue by KaiserCh** [avisota/contao-core#234]
Im aktuellen Composer-Build löst der Versuch sich die Empfängerliste über die Empfängerquellen anzusehen, eine unhandled exception aus => weißer Fehlerbildschirm. Das Problem ist, dass in der genannten Datei/Methode tatsächlich ein Objekt der Klasse "Avisota\Contao\Salutation\SalutationRecipientSource" übergeben wird, obwohl ein "RecipientsRecipientSource" erwartet wird.

> PHP Fatal error:  Call to undefined method Avisota\Contao\Salutation\SalutationRecipientSource::setUnsubscribeUrlPattern() in ***/composer/vendor/avisota/contao-subscription-recipient/src/RecipientSource/RecipientsRecipientSourceFactory.php on line 130

Wenn ich vor Zeile 130 Folgendes ergänze, crasht der ganze Spaß nicht mehr, aber ich weiß noch nicht welche weiteren Folgen die Änderung hat:

```
if(!is_a($recipientSource, "RecipientsRecipientSource")) {
    $recipientSource = $recipientSource->getRecipientSource();
}
```

**Comment by baumannsven** [comment]
Fix in https://github.com/avisota/contao-subscription-recipient/commit/ebdc88e5e8f41c1b0e81cf499649bb16e031ca6d
